### ISSUE TITLE
Bot not working

### ISSUE THREAD

**Issue by dankstarr** [michaelrinderle/easy_apply#8]
I get the following error after running 'dotnet run'  
C:\Users\wasim\OneDrive\Projects\easy_apply\src\EasyApply\Factories\DriverFactory.cs(73,29): warning CS8629: Nullable value type may be null. [C:\Users\wasim\OneDrive\Projects\easy_apply\src\EasyApply\EasyApply.csproj]
C:\Users\wasim\OneDrive\Projects\easy_apply\src\EasyApply\Factories\DriverFactory.cs(76,29): warning CS8629: Nullable value type may be null. [C:\Users\wasim\OneDrive\Projects\easy_apply\src\EasyApply\EasyApply.csproj]
[*] EasyApply v1.0
[*] Written by the Michael Rinderle <michael@sofdigital.net>

The firefox browser just closes and chromedriver doesn't run at all. 
can you please include a detailed readme on how to run the project and install the prerequisites.

**Comment by michaelrinderle** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings

**Comment by michaelrinderle** [comment]
What have you done to try and figure it out yourself?
